"""kaa

Revision ID: 34236be43f0c
Revises: 649ab90ea863
Create Date: 2024-05-02 08:00:58.744342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34236be43f0c'
down_revision = '649ab90ea863'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wiki', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resposta_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_resposta_id', 'resposta', ['resposta_id'], ['id_resposta'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wiki', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('resposta_id')

    # ### end Alembic commands ###
