"""adwa

Revision ID: 649ab90ea863
Revises: 79ba845c854f
Create Date: 2024-05-02 07:49:51.959413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '649ab90ea863'
down_revision = '79ba845c854f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resposta',
    sa.Column('id_resposta', sa.Integer(), nullable=False),
    sa.Column('resposta', sa.String(), nullable=True),
    sa.Column('wiki_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['wiki_id'], ['wiki.id'], ),
    sa.PrimaryKeyConstraint('id_resposta')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resposta')
    # ### end Alembic commands ###
