"""first

Revision ID: 79ba845c854f
Revises: 
Create Date: 2024-04-30 11:12:45.710984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79ba845c854f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wiki',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_envio', sa.DateTime(), nullable=True),
    sa.Column('nickname', sa.String(), nullable=True),
    sa.Column('titulo', sa.String(), nullable=True),
    sa.Column('mensagem', sa.String(), nullable=True),
    sa.Column('curtidas', sa.Integer(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wiki')
    # ### end Alembic commands ###
