"""agga

Revision ID: 8dd828f3bea7
Revises: 34236be43f0c
Create Date: 2024-05-02 08:10:47.628622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dd828f3bea7'
down_revision = '34236be43f0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wiki', schema=None) as batch_op:
        batch_op.drop_constraint('fk_resposta_id', type_='foreignkey')
        batch_op.drop_column('resposta_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wiki', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resposta_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_resposta_id', 'resposta', ['resposta_id'], ['id_resposta'])

    # ### end Alembic commands ###
