"""feliepggaag

Revision ID: ca60e67a9adb
Revises: 8dd828f3bea7
Create Date: 2024-05-02 08:26:06.224949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca60e67a9adb'
down_revision = '8dd828f3bea7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resposta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nickname', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resposta', schema=None) as batch_op:
        batch_op.drop_column('nickname')

    # ### end Alembic commands ###
